version: '3'
services:
  confluence:
    image: atlassian/confluence-server:7.15.1
    ports:
      - "8090:8090"
      - "8091:8091"
      - "5005:5005"
    environment:
      - JVM_SUPPORT_RECOMMENDED_ARGS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=confluence