version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:14.7.6-ce.0'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        gitlab_rails['omniauth_enabled'] = true
        gitlab_rails['omniauth_allow_single_sign_on'] = ['github']
        gitlab_rails['omniauth_block_auto_created_users'] = false
        gitlab_rails['omniauth_providers'] = [{"name" => "github","app_id" => "0fed7d7583c680d1b2ff","app_secret" => "519c79a6eee79e372f24ded19558417c6a3b0e7c","args" => { "scope" => "user:email" }}]
    ports:
      - '8080:80'
      - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
